name = "Test_package"
uuid = "cf1f3974-34be-444a-be67-449ea3f36d04"
authors = ["Hauke <h.uhde@tu-braunschweig.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1.11.0"
Revise = "3.8.1"
StaticArrays = "1.9.14"
